// <auto-generated />
using System;
using BcaLabExam2024.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BcaLabExam2024.Persistence.Migrations
{
    [DbContext(typeof(ExamDbContext))]
    [Migration("20240317082608_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BcaLabExam2024.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AnnualIncome")
                        .HasPrecision(14, 4)
                        .HasColumnType("decimal(14,4)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnnualIncome = 100000m,
                            DateOfBirth = new DateTime(1969, 3, 17, 14, 11, 8, 85, DateTimeKind.Local).AddTicks(3835),
                            Email = "",
                            FirstName = "Tony",
                            LastName = "Stark",
                            PhoneNumber = "9876333345"
                        },
                        new
                        {
                            Id = 2,
                            AnnualIncome = 100000m,
                            DateOfBirth = new DateTime(1974, 3, 17, 14, 11, 8, 85, DateTimeKind.Local).AddTicks(3854),
                            Email = "",
                            FirstName = "Thor",
                            LastName = "Odinson",
                            PhoneNumber = "9887633333"
                        },
                        new
                        {
                            Id = 3,
                            AnnualIncome = 100000m,
                            DateOfBirth = new DateTime(1980, 3, 17, 14, 11, 8, 85, DateTimeKind.Local).AddTicks(3857),
                            Email = "",
                            FirstName = "Bruce",
                            LastName = "Banner",
                            PhoneNumber = "9876333344"
                        },
                        new
                        {
                            Id = 4,
                            AnnualIncome = 100000m,
                            DateOfBirth = new DateTime(2004, 3, 17, 14, 11, 8, 85, DateTimeKind.Local).AddTicks(3858),
                            Email = "",
                            FirstName = "Peter",
                            LastName = "Parker",
                            PhoneNumber = "9873444452"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
